### ISSUE TITLE
Is this project still active?

### ISSUE THREAD

**Issue by zarry** [sensu/sensu-admin#115]
Just wondering the state of this project.

I am submitted a pull-request 4 months ago fixing the chef cookbook.  It has not been acknowledged or looked at.

I also don't believe this application works with the latest version of sensu 0.13.  I have it deployed and can't seem to get it to connect to the api.  

Any update would be great.  Just trying to figure out if this is a viable product to use or if we should focus our attention elsewhere.

Thanks!

**Comment by jszaszvari** [comment]
I'd consider this dead

**Comment by zarry** [comment]
Yup, I have moved on to uchiwa. Forgot this was open. Thanks.
